service: apigw-websocket-sample

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  connectHandler:
    handler: handler.connect_handler
    events:
      - websocket: $connect
  actionHandler:
    handler: handler.action_handler
    events:
      - websocket: actionRoute
  disconnectHandler:
    handler: handler.disconnect_handler
    events:
      - websocket: $disconnect
  defaultHandler:
    handler: handler.default_handler
    events:
      - websocket: $default
